language: go

os:
  - linux
  - osx

go:
  - "1.9"
  - "1.10"
  - "1.11"

script:
  - go test -race -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)
